/* The Readings: the teachings, from their authoring files to the reader.

   .scripts/plans/teachings/<planId>.json is the authoring source, written only
   by .scripts/teachings/land-batch.js:
     { plan, div, days: [{ d, label, key, ref, at, s, by, by2?, hedge?, src, batch }] }
   It grows a batch at a time. The reader sees a plan's teachings only when
   the set is complete and passes the gate (.scripts/check-teachings.js); then
   the build writes js/texts/teachings/<planId>.js
     FLTextPut("teachings", "<planId>", { plan, div, days: [{ d, at, ref, key, s, by }] })
   and lists it in FL_PLANS.teach[planId] = { v: <hash of the file>, n: <days> },
   so the reader asks for it under its own ?v= and a new set replaces a cached one.

   A set still in progress is written instead to js/texts/teachings/_preview/,
   which git ignores (so neither the repo nor the wing ever carries it), with a
   null for each day not yet landed. The reader loads it only on
   #/hall/<planId> with ?preview=teachings in the address. */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const C = require('./config');

const SRC_DIR = path.join(__dirname, 'teachings');
const OUT_DIR = path.join(C.ROOT, 'js', 'texts', 'teachings');
const PREVIEW_DIR = path.join(OUT_DIR, '_preview');

function readSets() {
  const out = {};
  if (!fs.existsSync(SRC_DIR)) return out;
  fs.readdirSync(SRC_DIR).filter(f => /^[a-z]+\.json$/.test(f)).sort().forEach(f => {
    const set = JSON.parse(fs.readFileSync(path.join(SRC_DIR, f), 'utf8'));
    const id = f.replace(/\.json$/, '');
    if (set.plan !== id) throw new Error('teachings/' + f + ': plan is ' + JSON.stringify(set.plan) + ', expected ' + JSON.stringify(id));
    out[id] = set;
  });
  return out;
}

/* days[d - 1] is day d's teaching, or null where a set in progress has none
   yet: { d, at, ref, key, s, by }, the shape check-plans.js holds the shipped
   file to, with by the commentator's display name from roster.json. */
function payloadOf(set, nDays) {
  const people = require(path.join(C.ROOT, '.scripts', 'teachings', 'roster.json')).people;
  const byDay = {};
  set.days.forEach(e => {
    const p = people[e.by];
    byDay[e.d] = { d: e.d, at: e.at, ref: e.ref, key: e.key, s: e.s, by: p ? p.name : e.by };
  });
  const days = [];
  for (let d = 1; d <= nDays; d++) days.push(byDay[d] || null);
  return { plan: set.plan, div: set.div, days: days };
}

function fileText(part, payload, note) {
  return '/* First Light: ' + note + '. Generated by .scripts/plans/build-plans.js from\n' +
    '   .scripts/plans/teachings/' + payload.plan + '.json; do not edit by hand. */\n' +
    'FLTextPut("teachings", ' + JSON.stringify(part) + ', ' + JSON.stringify(payload) + ');\n';
}
function hashOf(text) { return crypto.createHash('sha1').update(text).digest('hex').slice(0, 10); }

/* Given the built plans ({ id: { plan: { div, days } } }) and a checker
   (check-teachings.js checkSet), decide what each set produces. Nothing is
   written here. Returns { teach, files: [{ path, text }], stale: [paths],
   report: [lines], errors: [lines] }. */
function planTeachings(all, checkSet) {
  const sets = readSets();
  const teach = {}, files = [], report = [], errors = [];
  const want = new Set();
  Object.keys(sets).forEach(id => {
    const set = sets[id], built = all[id];
    if (!built) { errors.push('teachings/' + id + '.json: no such plan'); return; }
    const nDays = built.plan.days.length / 3;
    const res = checkSet(set, { full: false });
    const complete = set.days.length === nDays;
    if (res.errors.length) {
      errors.push('teachings/' + id + '.json fails the gate (' + res.errors.length + '):\n    ' + res.errors.slice(0, 12).join('\n    '));
      return;
    }
    if (set.div !== built.plan.div) { errors.push('teachings/' + id + '.json: written against division ' + set.div + ', the plan is ' + built.plan.div); return; }
    if (complete) {
      const text = fileText(id, payloadOf(set, nDays), 'the teachings of ' + id);
      const p = path.join(OUT_DIR, id + '.js');
      files.push({ path: p, text });
      want.add(p);
      teach[id] = { v: hashOf(text), n: nDays };
      report.push(id + ': ' + nDays + ' of ' + nDays + ', complete, listed (v ' + teach[id].v + ')');
    } else {
      const text = fileText('_preview/' + id, payloadOf(set, nDays),'a PREVIEW of the teachings of ' + id + ' (' + set.days.length + ' of ' + nDays + ')');
      const p = path.join(PREVIEW_DIR, id + '.js');
      files.push({ path: p, text });
      want.add(p);
      report.push(id + ': ' + set.days.length + ' of ' + nDays + ', in progress, preview only (/?nosw&preview=teachings#/hall/' + id + ')');
    }
  });
  /* a file whose set is gone, or has moved from preview to complete */
  const stale = [];
  [OUT_DIR, PREVIEW_DIR].forEach(dir => {
    if (!fs.existsSync(dir)) return;
    fs.readdirSync(dir).filter(f => /\.js$/.test(f)).forEach(f => {
      const p = path.join(dir, f);
      if (!want.has(p)) stale.push(p);
    });
  });
  return { teach, files, stale, report, errors };
}

module.exports = { readSets, payloadOf, fileText, hashOf, planTeachings, SRC_DIR, OUT_DIR, PREVIEW_DIR };
