/* The Readings: the teachings, from their authoring files to the reader.

   .scripts/plans/teachings/<planId>.json is the authoring source, written only
   by .scripts/teachings/land-batch.js:
     { plan, div, days: [{ d, label, key, ref, at, s, by, by2?, hedge?, src, batch }] }
   It grows a batch at a time. The reader sees a plan's teachings only when
   the set is complete and passes the gate (.scripts/check-teachings.js); then
   the build writes js/texts/teachings/<planId>.js
     FLTextPut("teachings", "<planId>", { plan, div, days: [{ d, at, ref, key, s, by }] })
   and lists it in FL_PLANS.teach[planId] = { v: <hash of the file>, n: <days> },
   so the reader asks for it under its own ?v= and a new set replaces a cached one.

   A set still in progress is written instead to js/texts/teachings/_preview/,
   which git ignores (so neither the repo nor the wing ever carries it), with a
   null for each day not yet landed. The reader loads it only on
   #/hall/<planId> with ?preview=teachings in the address. */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const C = require('./config');

const SRC_DIR = path.join(__dirname, 'teachings');
const OUT_DIR = path.join(C.ROOT, 'js', 'texts', 'teachings');
const PREVIEW_DIR = path.join(OUT_DIR, '_preview');

function readSets() {
  const out = {};
  if (!fs.existsSync(SRC_DIR)) return out;
  fs.readdirSync(SRC_DIR).filter(f => /^[a-z]+\.json$/.test(f)).sort().forEach(f => {
    const set = JSON.parse(fs.readFileSync(path.join(SRC_DIR, f), 'utf8'));
    const id = f.replace(/\.json$/, '');
    if (set.plan !== id) throw new Error('teachings/' + f + ': plan is ' + JSON.stringify(set.plan) + ', expected ' + JSON.stringify(id));
    out[id] = set;
  });
  return out;
}

/* days[d - 1] is day d's teaching, or null where a set in progress has none
   yet: { d, at, ref, key, s, by }, the shape check-plans.js holds the shipped
   file to, with by the commentator's display name from roster.json. */
function payloadOf(set, nDays) {
  const people = require(path.join(C.ROOT, '.scripts', 'teachings', 'roster.json')).people;
  const byDay = {};
  set.days.forEach(e => {
    const p = people[e.by];
    byDay[e.d] = { d: e.d, at: e.at, ref: e.ref, key: e.key, s: e.s, by: p ? p.name : e.by };
  });
  const days = [];
  for (let d = 1; d <= nDays; d++) days.push(byDay[d] || null);
  return { plan: set.plan, div: set.div, days: days };
}

function fileText(part, payload, note) {
  return '/* First Light: ' + note + '. Generated by .scripts/plans/build-plans.js from\n' +
    '   .scripts/plans/teachings/' + payload.plan + '.json; do not edit by hand. */\n' +
    'FLTextPut("teachings", ' + JSON.stringify(part) + ', ' + JSON.stringify(payload) + ');\n';
}
function hashOf(text) { return crypto.createHash('sha1').update(text).digest('hex').slice(0, 10); }

/* The owner's holds: .scripts/plans/teachings/_hold.json, { "<planId>": "<why>" }.
   A set named there is never listed for the reader, however complete, until
   the owner has read it and the line is taken out (the plan's checkpoints:
   the Qur'an's hard days, the Tanakh's sample, the Bible's pairs). */
function readHold() {
  const f = path.join(SRC_DIR, '_hold.json');
  return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : {};
}

/* Given the built plans ({ id: { plan: { div, days } } }) and a checker
   (check-teachings.js checkSet), decide what each set produces. Nothing is
   written here. Returns { teach, files: [{ path, text }], stale: [paths],
   report: [lines], errors: [lines] }. */
function planTeachings(all, checkSet) {
  const sets = readSets();
  const HOLD = readHold();
  const teach = {}, files = [], report = [], errors = [];
  const want = new Set();
  Object.keys(sets).forEach(id => {
    const set = sets[id], built = all[id];
    if (!built) { errors.push('teachings/' + id + '.json: no such plan'); return; }
    const nDays = built.plan.days.length / 3;
    const res = checkSet(set, { full: false });
    const complete = set.days.length === nDays;
    if (res.errors.length) {
      errors.push('teachings/' + id + '.json fails the gate (' + res.errors.length + '):\n    ' + res.errors.slice(0, 12).join('\n    '));
      return;
    }
    if (set.div !== built.plan.div) { errors.push('teachings/' + id + '.json: written against division ' + set.div + ', the plan is ' + built.plan.div); return; }
    /* a complete set held for the owner's reading stays in preview */
    if (complete && HOLD[id]) {
      const text = fileText('_preview/' + id, payloadOf(set, nDays), 'a PREVIEW of the teachings of ' + id + ', complete and held for the owner');
      const p = path.join(PREVIEW_DIR, id + '.js');
      files.push({ path: p, text });
      want.add(p);
      report.push(id + ': ' + nDays + ' of ' + nDays + ', complete, HELD (' + HOLD[id] + '); preview only (/?nosw&preview=teachings#/hall/' + id + ')');
    } else if (complete) {
      const text = fileText(id, payloadOf(set, nDays), 'the teachings of ' + id);
      const p = path.join(OUT_DIR, id + '.js');
      files.push({ path: p, text });
      want.add(p);
      teach[id] = { v: hashOf(text), n: nDays };
      report.push(id + ': ' + nDays + ' of ' + nDays + ', complete, listed (v ' + teach[id].v + ')');
    } else {
      const text = fileText('_preview/' + id, payloadOf(set, nDays),'a PREVIEW of the teachings of ' + id + ' (' + set.days.length + ' of ' + nDays + ')');
      const p = path.join(PREVIEW_DIR, id + '.js');
      files.push({ path: p, text });
      want.add(p);
      report.push(id + ': ' + set.days.length + ' of ' + nDays + ', in progress, preview only (/?nosw&preview=teachings#/hall/' + id + ')');
    }
  });
  /* a file whose set is gone, or has moved from preview to complete */
  const stale = [];
  [OUT_DIR, PREVIEW_DIR].forEach(dir => {
    if (!fs.existsSync(dir)) return;
    fs.readdirSync(dir).filter(f => /\.js$/.test(f)).forEach(f => {
      const p = path.join(dir, f);
      if (!want.has(p)) stale.push(p);
    });
  });
  return { teach, files, stale, report, errors };
}

/* ---- the tradition courses ----
   .scripts/plans/teachings/course-<tr>.json, written only by land-batch.js:
     { plan: "course-<tr>", div, days: [{ d, label, key, ref, at, s, by, by2?,
       hedge?, src, work, pd, batch, id }] }
   where work and pd are the work and its day that hold the key line. A
   complete set that passes the gate becomes js/texts/courses/<tr>.js
     FLTextPut("courses", "<tr>", { tradition, days: [{ d, sec, i, line, ref,
       loc: { plan, at }, s, by }] })
   (the shape check-plans.js's checkCourses holds the shipped file to; the
   titles and glosses stay in FL_TRADITIONS), listed as FL_PLANS.courses[tr]
   = { v, n }. A set in progress goes to js/texts/courses/_preview/<tr>.js,
   which git ignores, read on #/hall/course-<tr> with ?preview=teachings. */
const COURSE_OUT = path.join(C.ROOT, 'js', 'texts', 'courses');
const COURSE_PREVIEW = path.join(COURSE_OUT, '_preview');

function readCourseSets() {
  const out = {};
  if (!fs.existsSync(SRC_DIR)) return out;
  fs.readdirSync(SRC_DIR).filter(f => /^course-[a-z]+\.json$/.test(f)).sort().forEach(f => {
    const set = JSON.parse(fs.readFileSync(path.join(SRC_DIR, f), 'utf8'));
    const id = f.replace(/\.json$/, '');
    if (set.plan !== id) throw new Error('teachings/' + f + ': plan is ' + JSON.stringify(set.plan) + ', expected ' + JSON.stringify(id));
    out[id] = set;
  });
  return out;
}

/* days[d - 1] is day d's line and sentence, or null where a set in progress
   has none yet. The line's place is read again from the texts (the gate has
   held work and pd to it). */
function coursePayload(set, corpus) {
  const people = require(path.join(C.ROOT, '.scripts', 'teachings', 'roster.json')).people;
  const id = set.plan, entries = corpus.courseEntries(id);
  const byDay = {};
  set.days.forEach(e => { byDay[e.d] = e; });
  const days = entries.map(x => {
    const e = byDay[x.d];
    if (!e) return null;
    const loc = corpus.locateCourse(id, e.d, e.key, e.ref);
    const p = people[e.by];
    return { d: x.d, sec: x.sec, i: x.i, line: e.key, ref: e.ref, loc: { plan: loc.work, at: e.at }, s: e.s, by: p ? p.name : e.by };
  });
  return { tradition: corpus.courseTr(id), days };
}
function courseFileText(part, payload, note, id) {
  return '/* First Light: ' + note + '. Generated by .scripts/plans/build-plans.js from\n' +
    '   .scripts/plans/teachings/' + id + '.json; do not edit by hand. */\n' +
    'FLTextPut("courses", ' + JSON.stringify(part) + ', ' + JSON.stringify(payload) + ');\n';
}

/* As planTeachings, for the courses: { courses, files, stale, report, errors }. */
function planCourses(checkSet) {
  const corpus = require(path.join(C.ROOT, '.scripts', 'teachings', 'corpus'));
  const sets = readCourseSets();
  const HOLD = readHold();
  const courses = {}, files = [], report = [], errors = [];
  const want = new Set();
  Object.keys(sets).forEach(id => {
    const set = sets[id];
    if (!corpus.isCourse(id)) { errors.push('teachings/' + id + '.json: no such course (roster.json courses)'); return; }
    const tr = corpus.courseTr(id), n = corpus.courseEntries(id).length;
    const res = checkSet(set, { full: false });
    if (res.errors.length) {
      errors.push('teachings/' + id + '.json fails the gate (' + res.errors.length + '):\n    ' + res.errors.slice(0, 12).join('\n    '));
      return;
    }
    if (set.div !== corpus.courseDiv(id)) { errors.push('teachings/' + id + '.json: written against chamber ' + set.div + ', the chamber is ' + corpus.courseDiv(id)); return; }
    const payload = coursePayload(set, corpus);
    /* a complete course held for the owner's reading stays in preview, as a
       held work does */
    if (set.days.length === n && HOLD[id]) {
      const text = courseFileText('_preview/' + tr, payload, 'a PREVIEW of the course of the ' + tr + ' tradition, complete and held for the owner', id);
      const p = path.join(COURSE_PREVIEW, tr + '.js');
      files.push({ path: p, text });
      want.add(p);
      report.push(id + ': ' + n + ' of ' + n + ', complete, HELD (' + HOLD[id] + '); preview only (/?nosw&preview=teachings#/hall/' + id + ')');
    } else if (set.days.length === n) {
      const text = courseFileText(tr, payload, 'the course of the ' + tr + ' tradition', id);
      const p = path.join(COURSE_OUT, tr + '.js');
      files.push({ path: p, text });
      want.add(p);
      courses[tr] = { v: hashOf(text), n };
      report.push(id + ': ' + n + ' of ' + n + ', complete, listed (v ' + courses[tr].v + ')');
    } else {
      const text = courseFileText('_preview/' + tr, payload, 'a PREVIEW of the course of the ' + tr + ' tradition (' + set.days.length + ' of ' + n + ')', id);
      const p = path.join(COURSE_PREVIEW, tr + '.js');
      files.push({ path: p, text });
      want.add(p);
      report.push(id + ': ' + set.days.length + ' of ' + n + ', in progress, preview only (/?nosw&preview=teachings#/hall/' + id + ')');
    }
  });
  const stale = [];
  [COURSE_OUT, COURSE_PREVIEW].forEach(dir => {
    if (!fs.existsSync(dir)) return;
    fs.readdirSync(dir).filter(f => /\.js$/.test(f)).forEach(f => {
      const p = path.join(dir, f);
      if (!want.has(p)) stale.push(p);
    });
  });
  return { courses, files, stale, report, errors };
}

module.exports = { readSets, payloadOf, fileText, hashOf, planTeachings, planCourses, readCourseSets, coursePayload, SRC_DIR, OUT_DIR, PREVIEW_DIR, COURSE_OUT, COURSE_PREVIEW };
