/* Build js/data-cities.js — birth places for the chart.

   AUTHORING TOOL, not a build step. Run by hand; output committed.

   A natal chart needs latitude, longitude, and the UTC offset in force at the moment
   of birth. The first two are geography. The third is history, and it is the part
   that goes wrong: offsets have changed, sometimes more than once, and a chart drawn
   with today's rule for a 1974 American birth is an hour out — enough to move the
   Ascendant by a whole sign.

   The tempting fix is to bundle the IANA time-zone database. That is ~450 KB to
   duplicate something every target browser already ships and keeps patched: given an
   IANA zone name and an instant, Intl.DateTimeFormat returns the correct HISTORICAL
   offset, including the 1974 US year-round-DST year. So each city carries only its
   zone NAME and the browser does the arithmetic.

   Source: kevinroberts/city-timezones, which is GeoNames-derived and already pairs
   each city with its IANA zone.

   Usage: node .scripts/build-cities.js [count]
*/
'use strict';
const fs = require('fs');
const path = require('path');

const SRC = 'https://raw.githubusercontent.com/kevinroberts/city-timezones/master/data/cityMap.json';
const CACHE = path.join(__dirname, '.cache', 'cityMap.json');
const OUT = path.join(__dirname, '..', 'js', 'data-cities.js');
const COUNT = parseInt(process.argv[2] || '4000', 10);

(async () => {
  let raw;
  if (fs.existsSync(CACHE)) raw = fs.readFileSync(CACHE, 'utf8');
  else {
    console.log('  fetching city list…');
    const res = await fetch(SRC, { headers: { 'User-Agent': 'FirstLight/1.0 (one-time data bake)' } });
    raw = await res.text();
    fs.mkdirSync(path.dirname(CACHE), { recursive: true });
    fs.writeFileSync(CACHE, raw);
  }

  const all = JSON.parse(raw).filter(c =>
    c && c.city_ascii && c.timezone && Number.isFinite(c.lat) && Number.isFinite(c.lng));

  /* Sort by population and keep the head. A birth place absent from the list is
     handled by manual coordinate entry, so the tail buys very little. */
  all.sort((a, b) => (b.pop || 0) - (a.pop || 0));

  const seen = new Set();
  const picked = [];
  for (const c of all) {
    const key = c.city_ascii + '|' + c.iso2 + '|' + c.province;
    if (seen.has(key)) continue;
    seen.add(key);
    picked.push(c);
    if (picked.length >= COUNT) break;
  }

  /* Zones repeat heavily — a few hundred distinct names across thousands of cities —
     so store them once and reference by index. */
  const zones = [];
  const zoneIx = new Map();
  const rows = picked.map(c => {
    if (!zoneIx.has(c.timezone)) { zoneIx.set(c.timezone, zones.length); zones.push(c.timezone); }
    return [
      c.city_ascii,
      c.iso2 || '',
      Math.round(c.lat * 1000) / 1000,     // ~110 m; far finer than anyone knows their birth address
      Math.round(c.lng * 1000) / 1000,
      zoneIx.get(c.timezone)
    ];
  });

  const body =
`/* First Light — birth places.

   Generated by .scripts/build-cities.js. Do not hand-edit.

   ${rows.length} cities by population, ${zones.length} distinct IANA zones.
   Rows are [name, ISO2, lat, lon, zoneIndex] — flat arrays rather than objects
   because repeating five key names ${rows.length} times costs more than the data.

   Coordinates are rounded to 3 decimals (~110 m). That is far below the precision
   anyone actually has about their own birth, where the stated TIME is the dominant
   error: "about three in the afternoon" is plus or minus half an hour, which moves
   the Ascendant roughly seven degrees. The app says so rather than implying more
   precision than exists. */

var FL_ZONES = ${JSON.stringify(zones)};

var FL_CITIES = [
${rows.map(r => JSON.stringify(r)).join(',\n')}
];
`;

  fs.writeFileSync(OUT, body, 'utf8');
  console.log('  ' + rows.length + ' cities · ' + zones.length + ' zones · ' +
              (Buffer.byteLength(body) / 1024).toFixed(0) + ' KB → js/data-cities.js');
  console.log('  smallest population kept: ' + (picked[picked.length - 1].pop || 0).toLocaleString());
})();
