/* Build js/data-library.js from the baked texts.

   The library index is small — book names, chapter counts, file sizes, attribution —
   so it ships precached and the Library renders its whole structure offline without
   loading a single byte of scripture. The text itself loads only when opened.

   Run after fetch-texts.js:  node .scripts/build-library.js
*/
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const TEXTS = path.join(ROOT, 'js', 'texts');

/* Order is shelf order, and it is deliberate: the traditions appear roughly in the
   order their texts were first set down, which is the least tendentious ordering
   available and quietly teaches something true. */
const SHELF = ['rigveda', 'tanakh', 'upanishads', 'dhammapada', 'analects', 'tao',
               'zhuangzi', 'gita', 'bible', 'quran'];

const lib = {};
let grand = 0;

for (const work of SHELF) {
  const dir = path.join(TEXTS, work);
  const idxFile = path.join(dir, 'index.json');
  if (!fs.existsSync(idxFile)) { console.log('  – ' + work + ' not baked yet, skipping'); continue; }

  const idx = JSON.parse(fs.readFileSync(idxFile, 'utf8'));
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.js'));
  const bytes = files.reduce((s, f) => s + fs.statSync(path.join(dir, f)).size, 0);
  grand += bytes;

  lib[work] = {
    title: idx.title,
    translation: idx.translation,
    license: idx.license,
    source: idx.source,
    bytes: bytes,
    parts: idx.books || (idx.whole ? [{ part: 'all' }] : []),
    surahs: idx.surahs,
    chapters: idx.chapters
  };
  console.log('  ' + work.padEnd(12) + String(files.length).padStart(3) + ' files  ' +
              (bytes / 1048576).toFixed(2).padStart(6) + ' MB');
}

const out =
`/* First Light — the library index.

   Generated by .scripts/build-library.js from the baked texts. Do not edit by hand;
   re-run the generator instead.

   Small on purpose: this is precached with the app shell so the Library can show
   every work, book and chapter offline, before any scripture is loaded. The text
   itself lives in js/texts/<work>/<part>.js and loads only when a passage is opened.
   Total library on disk: ${(grand / 1048576).toFixed(2)} MB. */

var FL_LIBRARY = ${JSON.stringify(lib, null, 1)};
`;

fs.writeFileSync(path.join(ROOT, 'js', 'data-library.js'), out, 'utf8');
console.log('\n  → js/data-library.js  (' + (Buffer.byteLength(out) / 1024).toFixed(1) + ' KB index for ' +
            (grand / 1048576).toFixed(2) + ' MB of scripture)');
